### ISSUE TITLE
Arknights Integrated Strategies for Complete Endings

### ISSUE THREAD

**Issue by skzidan** [reKelin/Arknights-Integrated-Strategies-Prospective-Investment-Script#3]
Do you have Integrated Strategies for Completing Endings (Total 4 endings)?

**Comment by reKelin** [comment]
You can find it on [prts](https://prts.wiki) or [fandom wiki](https://arknights.fandom.com/wiki/Integrated_Strategies), or just google it.

**Comment by skzidan** [comment]
i meant script

**Comment by reKelin** [comment]
[MAA](https://github.com/MaaAssistantArknights/MaaAssistantArknights) can do it, but there is a high probability that it can't beat the BOSS.
